_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 9
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 103
            "2":
                - 1
                - 2
                - 3
                - 5
                - 9
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 103
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.8
            "5": 0.18.1
            "6": 4.43.0
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
